Repository FRCTeam31/Swerve_TestBench, pull requests merged in 2023-02, with the labels that each got.

#8 i mad a cod that rests the gyro
  src/main/java/frc/robot/Robot.java
Labels: drive

#15 i cha the ded badnd to 0.1
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/PrimeSwerveModuleSubsystem.java
Labels: bug, drive

#23 Added lazy classes for common CAN devices.
  src/main/java/frc/robot/subsystems/PrimeSwerveModuleSubsystem.java
  src/main/java/prime/movers/LazyCANSparkMax.java
  src/main/java/prime/movers/LazySolenoid.java
  src/main/java/prime/movers/LazyWPITalonFX.java
  src/main/java/prime/movers/LazyWPITalonSRX.java
  vendordeps/REVLib.json
Labels: Optimization

#26 Jace drive shifter
  .vscode/launch.json
  .vscode/settings.json
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/DriveCommands.java
  src/main/java/frc/robot/config/DriveMap.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: drive
